/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "fpu_init.h"
#include "dht_22.h"
#include "i2c_lcd.h"
#include "mpu6050.h"
#include "telemetry.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"

QueueHandle_t xClimateQueue;
QueueHandle_t xGyroQueue;

SemaphoreHandle_t xI2C1_Mutex;


int main(void)
{
	FPU_Init();
	DHT22_Timer_Init();
	I2C_GPIO_Init();
	I2C_Config();


	xClimateQueue = xQueueCreate(5, sizeof(Climate_Payload_t));
	xI2C1_Mutex = xSemaphoreCreateMutex();
	xGyroQueue = xQueueCreate(5, sizeof(int16_t));

	if (xGyroQueue == NULL) {
	        while(1); // To trap the code if creation fails
	    }

	if( xClimateQueue != NULL){
		DHT22_Task_Init();
		LCD_Task_Init();
		uint8_t mpu_id = MPU6050_Identity_Check();
		MPU6050_Task_Init();
		vTaskStartScheduler();
	}


	while(1){}
}
