/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "fpu_init.h"
#include "dht_22.h"
#include "FreeRTOS.h"
#include "task.h"

DHT22_Data_t Current_Climate = {0.0f, 0.0f};


void vClimateTask(void *pvParameters){

	vTaskDelay(pdMS_TO_TICKS(2000));

	while(1){
		DHT22_Get_Data(&Current_Climate);
		vTaskDelay(pdMS_TO_TICKS(2000));  // delay to avoid overheating
	}
}

int main(void)
{
	FPU_Init();
	DHT22_Timer_Init();

	 xTaskCreate(vClimateTask, "Climate", 128, NULL, 1, NULL);

	vTaskStartScheduler();

	while(1){}
}
